In [9]:
import pandas as pd

data = {
    'Document': ['D1', 'D2', 'D3', 'D4'],
    'Text': [
        'people watch campus',
        'campusx watch campusx',
        'people write comment',
        'campusx write comment'
    ],
    'Target': [1, 1, 0, 0]
}

df = pd.DataFrame(data)

print(df)

  Document                   Text  Target
0       D1    people watch campus       1
1       D2  campusx watch campusx       1
2       D3   people write comment       0
3       D4  campusx write comment       0


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer()

In [16]:
bow = cv.fit_transform(df['Text'])

In [17]:
# vocab
print(cv.vocabulary_)

{'people': 3, 'watch': 4, 'campus': 0, 'campusx': 1, 'write': 5, 'comment': 2}


In [18]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 1 1 0]]
[[0 2 0 0 1 0]]


In [19]:
# it handle out of vocalbre 
cv.transform(["campusx wath and write comment of campusx"]).toarray()

array([[0, 2, 1, 0, 0, 1]])

In [23]:
import pandas as pd

df = pd.read_csv("../dataset.csv")

print(df.head())

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [30]:
cv2 = CountVectorizer(ngram_range=(5,5),max_features=500)

In [31]:
bow2 = cv2.fit_transform(df['review'])

In [32]:
# vocab
print(cv2.vocabulary_)

{'due to the fact that': np.int64(147), 'br br this movie is': np.int64(116), 'br br out of 10': np.int64(69), 'br br the only thing': np.int64(93), 'br br the acting is': np.int64(75), 'and the rest of the': np.int64(17), 'br the only thing that': np.int64(124), 'you will not be disappointed': np.int64(499), 'br br there are some': np.int64(104), 'this was one of the': np.int64(442), 'was one of the most': np.int64(461), 'the rest of the film': np.int64(390), 'if you re looking for': np.int64(203), 'this has got to be': np.int64(414), 'has got to be the': np.int64(174), 'br br the movie is': np.int64(87), 'at the same time br': np.int64(29), 'the same time br br': np.int64(394), 'for the rest of the': np.int64(161), 'for most of the film': np.int64(157), 'of the rest of the': np.int64(289), 'the fact that the film': np.int64(366), 'at the start of the': np.int64(32), 'the start of the film': np.int64(396), 'the first half of the': np.int64(372), 'first half of the film': np.int64(154)